export const FETCH_PRODCUTS = "FETCH_PRODCUTS";
export const FILTER_PRODUCTS_BY_GENDER = "FILTER_PRODUCTS_BY_GENDER";
export const FILTER_PRODUCTS_BY_BRAND = "FILTER_PRODUCTS_BY_BRAND";
export const FILTER_PRODUCTS_BY_CATEGORY = "FILTER_PRODUCTS_BY_CATEGORY";
export const FILTER_PRODUCTS_BY_COLOR = "FILTER_PRODUCTS_BY_COLOR";
export const FILTER_BUTTON = "FILTER_BUTTON";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";